# Generated by Django 4.0.1 on 2022-06-14 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0003_alter_booking_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrental.discount'),
        ),
    ]
