# Generated by Django 4.0.1 on 2022-06-14 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0004_alter_booking_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='from_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='ret_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
