# Generated by Django 4.0.1 on 2022-06-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0007_payment_payment_type_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
